//go:build darwin

package mimi

import (
	"testing"

	"github.com/vinq1911/gorch/model"
)

// TestFixturesLoadable verifies the Phase 0 golden fixtures
// (audio/testdata/mimi_fixtures.safetensors, generated by
// audio/export_mimi_fixtures.py) load through gorch's safetensors
// reader with the expected tensor names and shapes. Phases 2-5 build
// their golden tests on these.
func TestFixturesLoadable(t *testing.T) {
	sf, err := model.LoadSafetensors("../testdata/mimi_fixtures.safetensors")
	if err != nil {
		t.Fatalf("load fixtures: %v", err)
	}

	want := map[string][]int{
		"chirp_pcm":           {48000},
		"chirp_seanet":        {512, 50},
		"chirp_layer0":        {50, 512},
		"chirp_transformer":   {50, 512},
		"chirp_latent":        {512, 25},
		"chirp_stream_latent": {512, 25},
		"chirp_pooled":        {1024},
		"chirp_codes":         {32, 25},
		"chirp_codes8":        {8, 25},
		"chirp_quantized":     {512, 25},

		"long_pcm":             {288000},
		"long_seanet":          {512, 300},
		"long_layer0":          {300, 512},
		"long_transformer":     {300, 512},
		"long_latent":          {512, 150},
		"long_stream_latent":   {512, 150},
		"long_pooled":          {1024},
		"long_transformer_win": {300, 512},
		"long_latent_win":      {512, 150},
		"long_codes":           {32, 150},
		"long_codes8":          {8, 150},
		"long_quantized":       {512, 150},
	}

	if len(sf.Tensors) != len(want) {
		t.Errorf("fixture has %d tensors, want %d", len(sf.Tensors), len(want))
	}
	for name, shape := range want {
		tt, ok := sf.Tensors[name]
		if !ok {
			t.Errorf("missing fixture tensor %q", name)
			continue
		}
		got := tt.Shape()
		if len(got) != len(shape) {
			t.Errorf("%s: shape %v, want %v", name, got, shape)
			continue
		}
		for i := range shape {
			if got[i] != shape[i] {
				t.Errorf("%s: shape %v, want %v", name, got, shape)
				break
			}
		}
		if len(tt.Data()) == 0 {
			t.Errorf("%s: empty data", name)
		}
	}

	// Spot-check values are finite and non-degenerate: the pooled std
	// half of the chirp vector must be strictly positive.
	pooled := sf.Tensors["chirp_pooled"].Data()
	for i := 512; i < 1024; i++ {
		if !(pooled[i] > 0) {
			t.Fatalf("chirp_pooled[%d] = %v, want > 0 (std half)", i, pooled[i])
		}
	}
}
