//go:build darwin

package mimi

import (
	"testing"

	"github.com/vinq1911/gorch/model"
)

// TestFixturesLoadable verifies the Phase 0 golden fixtures
// (audio/testdata/mimi_fixtures.safetensors, generated by
// audio/export_mimi_fixtures.py) load through gorch's safetensors
// reader with the expected tensor names and shapes. Phases 2-5 build
// their golden tests on these.
func TestFixturesLoadable(t *testing.T) {
	sf, err := model.LoadSafetensors("../testdata/mimi_fixtures.safetensors")
	if err != nil {
		t.Fatalf("load fixtures: %v", err)
	}

	want := map[string][]int{
		"chirp_pcm":           {48000},
		"chirp_seanet":        {512, 50},
		"chirp_layer0":        {50, 512},
		"chirp_transformer":   {50, 512},
		"chirp_latent":        {512, 25},
		"chirp_stream_latent": {512, 25},
		"chirp_pooled":        {1024},
		"chirp_codes":         {32, 25},
		"chirp_codes8":        {8, 25},
		"chirp_quantized":     {512, 25},

		"long_pcm":             {288000},
		"long_seanet":          {512, 300},
		"long_layer0":          {300, 512},
		"long_transformer":     {300, 512},
		"long_latent":          {512, 150},
		"long_stream_latent":   {512, 150},
		"long_pooled":          {1024},
		"long_transformer_win": {300, 512},
		"long_latent_win":      {512, 150},
		"long_codes":           {32, 150},
		"long_codes8":          {8, 150},
		"long_quantized":       {512, 150},
	}

	if len(sf.Tensors) != len(want) {
		t.Errorf("fixture has %d tensors, want %d", len(sf.Tensors), len(want))
	}
	for name, shape := range want {
		tt, ok := sf.Tensors[name]
		if !ok {
			t.Errorf("missing fixture tensor %q", name)
			continue
		}
		got := tt.Shape()
		if len(got) != len(shape) {
			t.Errorf("%s: shape %v, want %v", name, got, shape)
			continue
		}
		for i := range shape {
			if got[i] != shape[i] {
				t.Errorf("%s: shape %v, want %v", name, got, shape)
				break
			}
		}
		if len(tt.Data()) == 0 {
			t.Errorf("%s: empty data", name)
		}
	}

	// Spot-check values are finite and non-degenerate: the pooled std
	// half of the chirp vector must be strictly positive.
	pooled := sf.Tensors["chirp_pooled"].Data()
	for i := 512; i < 1024; i++ {
		if !(pooled[i] > 0) {
			t.Fatalf("chirp_pooled[%d] = %v, want > 0 (std half)", i, pooled[i])
		}
	}
}

// TestDecoderFixturesLoadable verifies the plan-0007 Phase D0 decoder
// golden fixtures (audio/testdata/mimi_decoder_fixtures.safetensors,
// generated by audio/export_mimi_fixtures.py) load through gorch's
// safetensors reader with the expected tensor names and shapes.
// dec_layer0/dec_stage1/dec_stage2 are chirp-only (size budget; see the
// generator's D0 section comment). Phases D1-D3 build on these.
func TestDecoderFixturesLoadable(t *testing.T) {
	sf, err := model.LoadSafetensors("../testdata/mimi_decoder_fixtures.safetensors")
	if err != nil {
		t.Fatalf("load decoder fixtures: %v", err)
	}

	want := map[string][]int{
		"chirp_dec_upsampled":   {512, 50},
		"chirp_dec_layer0":      {50, 512},
		"chirp_dec_transformer": {50, 512},
		"chirp_dec_seanet0":     {1024, 50},
		"chirp_dec_stage1":      {512, 400},
		"chirp_dec_stage2":      {256, 2400},
		"chirp_dec_wav":         {48000},

		"long_dec_upsampled":       {512, 300},
		"long_dec_transformer":     {300, 512},
		"long_dec_seanet0":         {1024, 300},
		"long_dec_wav":             {288000},
		"long_dec_transformer_win": {300, 512},
		"long_dec_wav_win":         {288000},

		// Reference decodes of committed real-world Go tokens
		// (1920 samples per token).
		"rw_zero_alloy_dec_wav":   {19200},
		"rw_five_echo_dec_wav":    {21120},
		"rw_nine_shimmer_dec_wav": {21120},

		// ConvTranspose1d layout-pinning cases: weight is PyTorch's
		// (inC, outC/groups, k); out length (L-1)*stride + k.
		// ct_manifest rows: [kernel, stride, groups, has_bias].
		"ct_manifest": {6, 4},
		"ct_0_in":     {1, 3, 9},
		"ct_0_w":      {3, 5, 4},
		"ct_0_b":      {5},
		"ct_0_out":    {1, 5, 20},
		"ct_1_in":     {1, 6, 9}, // depthwise, bias-free (the upsample)
		"ct_1_w":      {6, 1, 4},
		"ct_1_out":    {1, 6, 20},
		"ct_2_in":     {1, 4, 5},
		"ct_2_w":      {4, 3, 16},
		"ct_2_b":      {3},
		"ct_2_out":    {1, 3, 48},
		"ct_3_in":     {1, 3, 7},
		"ct_3_w":      {3, 2, 12},
		"ct_3_b":      {2},
		"ct_3_out":    {1, 2, 48},
		"ct_4_in":     {1, 2, 8},
		"ct_4_w":      {2, 3, 3},
		"ct_4_b":      {3},
		"ct_4_out":    {1, 3, 10},
		"ct_5_in":     {1, 4, 6},
		"ct_5_w":      {4, 3, 8},
		"ct_5_b":      {6},
		"ct_5_out":    {1, 6, 28},
	}

	if len(sf.Tensors) != len(want) {
		t.Errorf("fixture has %d tensors, want %d", len(sf.Tensors), len(want))
	}
	for name, shape := range want {
		tt, ok := sf.Tensors[name]
		if !ok {
			t.Errorf("missing fixture tensor %q", name)
			continue
		}
		got := tt.Shape()
		if len(got) != len(shape) {
			t.Errorf("%s: shape %v, want %v", name, got, shape)
			continue
		}
		for i := range shape {
			if got[i] != shape[i] {
				t.Errorf("%s: shape %v, want %v", name, got, shape)
				break
			}
		}
		if len(tt.Data()) == 0 {
			t.Errorf("%s: empty data", name)
		}
	}

	// Spot-check the manifest pins the intended geometries.
	wantManifest := [][4]float32{
		{4, 2, 1, 1},
		{4, 2, 6, 0},
		{16, 8, 1, 1},
		{12, 6, 1, 1},
		{3, 1, 1, 1},
		{8, 4, 2, 1},
	}
	manifest := sf.Tensors["ct_manifest"].Data()
	for i, row := range wantManifest {
		for j, v := range row {
			if manifest[i*4+j] != v {
				t.Errorf("ct_manifest[%d][%d] = %v, want %v", i, j, manifest[i*4+j], v)
			}
		}
	}
}
