package embedded

import (
	"fmt"
	"io"
	"strings"
)

// LayerKind identifies a layer's op. The firmware hard-codes the topology
// (layer sequence) as a test fixture; only the numeric tables are emitted
// from the Go side.
type LayerKind uint8

const (
	KindLinearI8  LayerKind = 0 // fused-requant int8 layer
	KindLinearI32 LayerKind = 1 // classifier tail, produces int32 logits
	KindReLU      LayerKind = 2
)

// Layer is one op in a TinyModel. Fields are used only when they apply
// to the kind.
type Layer struct {
	Kind           LayerKind
	InDim, OutDim  int
	W              []int8  // row-major [OutDim][InDim]; Linear only
	B              []int32 // OutDim; Linear only
	M              int32   // Q0.31 requant multiplier; LinearI8 only
	S              uint8   // right-shift; LinearI8 only
}

// TinyModel is a tiny int8 MLP ready to export. It is deliberately a
// concrete, self-contained type so the harness can construct models
// without depending on gorch (which is darwin-only).
type TinyModel struct {
	InputDim int
	Layers   []Layer
}

// Infer runs the Go reference kernel and returns the argmax class. Uses
// two ping-pong int8 buffers plus one int32 buffer for the final logits;
// panics if the model is malformed. This function's output must match the
// firmware's output bit-for-bit.
func (m *TinyModel) Infer(x []int8) (class uint8, logits []int32) {
	if len(x) != m.InputDim {
		panic(fmt.Sprintf("embedded: input dim mismatch: got %d want %d", len(x), m.InputDim))
	}
	maxDim := m.InputDim
	for _, l := range m.Layers {
		if l.OutDim > maxDim {
			maxDim = l.OutDim
		}
	}
	a := make([]int8, maxDim)
	b := make([]int8, maxDim)
	copy(a, x)
	curDim := m.InputDim
	cur, nxt := a, b

	for i, l := range m.Layers {
		switch l.Kind {
		case KindLinearI8:
			LinearI8(l.W, l.B, l.M, l.S, l.InDim, l.OutDim, cur[:l.InDim], nxt[:l.OutDim])
			cur, nxt = nxt, cur
			curDim = l.OutDim
		case KindReLU:
			ReluI8(cur[:curDim])
		case KindLinearI32:
			if i != len(m.Layers)-1 {
				panic("embedded: LinearI32 must be the final layer")
			}
			out := make([]int32, l.OutDim)
			LinearI32(l.W, l.B, l.InDim, l.OutDim, cur[:l.InDim], out)
			return ArgmaxI32(out), out
		default:
			panic(fmt.Sprintf("embedded: unknown layer kind %d", l.Kind))
		}
	}
	panic("embedded: model has no classifier (LinearI32) tail")
}

// EmitCHeader writes a self-contained C header declaring:
//   - GM1_INPUT_DIM, GM1_NUM_CLASSES, GM1_MAX_DIM
//   - For each Linear layer: W{i}, B{i} (PROGMEM), and for LinearI8 the
//     M{i}/S{i} constants.
// The firmware that consumes this header declares its own topology (which
// ops run in what order) and simply references these tables.
func (m *TinyModel) EmitCHeader(w io.Writer, guard string) error {
	maxDim := m.InputDim
	var numClasses int
	for _, l := range m.Layers {
		if l.OutDim > maxDim {
			maxDim = l.OutDim
		}
		if l.Kind == KindLinearI32 {
			numClasses = l.OutDim
		}
	}
	if numClasses == 0 {
		return fmt.Errorf("embedded: model missing LinearI32 classifier tail")
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Generated by gorch/embedded. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "#ifndef %s\n#define %s\n\n", guard, guard)
	fmt.Fprintf(&b, "#include <stdint.h>\n")
	fmt.Fprintf(&b, "#ifdef __AVR__\n#include <avr/pgmspace.h>\n#else\n#define PROGMEM\n#endif\n\n")
	fmt.Fprintf(&b, "#define GM1_INPUT_DIM    %d\n", m.InputDim)
	fmt.Fprintf(&b, "#define GM1_NUM_CLASSES  %d\n", numClasses)
	fmt.Fprintf(&b, "#define GM1_MAX_DIM      %d\n\n", maxDim)

	for i, l := range m.Layers {
		switch l.Kind {
		case KindLinearI8, KindLinearI32:
			fmt.Fprintf(&b, "// Layer %d: %s %d->%d\n", i, layerKindName(l.Kind), l.InDim, l.OutDim)
			fmt.Fprintf(&b, "#define GM1_L%d_IN  %d\n", i, l.InDim)
			fmt.Fprintf(&b, "#define GM1_L%d_OUT %d\n", i, l.OutDim)
			writeI8Array(&b, fmt.Sprintf("GM1_W%d", i), l.W)
			writeI32Array(&b, fmt.Sprintf("GM1_B%d", i), l.B)
			if l.Kind == KindLinearI8 {
				fmt.Fprintf(&b, "#define GM1_M%d ((int32_t)%d)\n", i, l.M)
				fmt.Fprintf(&b, "#define GM1_S%d ((uint8_t)%d)\n\n", i, l.S)
			} else {
				b.WriteString("\n")
			}
		case KindReLU:
			fmt.Fprintf(&b, "// Layer %d: ReLU (no data)\n\n", i)
		}
	}

	fmt.Fprintf(&b, "#endif // %s\n", guard)
	_, err := io.WriteString(w, b.String())
	return err
}

func layerKindName(k LayerKind) string {
	switch k {
	case KindLinearI8:
		return "LinearI8"
	case KindLinearI32:
		return "LinearI32"
	case KindReLU:
		return "ReLU"
	}
	return "?"
}

func writeI8Array(w *strings.Builder, name string, data []int8) {
	fmt.Fprintf(w, "const int8_t %s[%d] PROGMEM = {", name, len(data))
	for i, v := range data {
		if i%16 == 0 {
			w.WriteString("\n  ")
		}
		fmt.Fprintf(w, "%d,", v)
	}
	w.WriteString("\n};\n")
}

func writeI32Array(w *strings.Builder, name string, data []int32) {
	fmt.Fprintf(w, "const int32_t %s[%d] PROGMEM = {", name, len(data))
	for i, v := range data {
		if i%8 == 0 {
			w.WriteString("\n  ")
		}
		fmt.Fprintf(w, "%d,", v)
	}
	w.WriteString("\n};\n")
}

// EmitInputHeader writes a C header with the test input as an int8 array.
func EmitInputHeader(w io.Writer, guard, name string, x []int8) error {
	var b strings.Builder
	fmt.Fprintf(&b, "// Generated by gorch/embedded. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "#ifndef %s\n#define %s\n\n#include <stdint.h>\n#ifdef __AVR__\n#include <avr/pgmspace.h>\n#else\n#define PROGMEM\n#endif\n\n", guard, guard)
	writeI8Array(&b, name, x)
	fmt.Fprintf(&b, "\n#endif // %s\n", guard)
	_, err := io.WriteString(w, b.String())
	return err
}
