//go:build darwin

package audio

import (
	"math"
	"os"
	"testing"

	g "github.com/vinq1911/gorch"
	"github.com/vinq1911/gorch/model"
)

// loadFixtures loads the golden fixtures generated by make_resample_fixtures.py.
// Shared by wav_test.go and resample_test.go.
func loadFixtures(t *testing.T) *model.SafetensorsFile {
	t.Helper()
	sf, err := model.LoadSafetensors("testdata/resample_fixtures.safetensors")
	if err != nil {
		t.Fatalf("load fixtures (regenerate with audio/make_resample_fixtures.py): %v", err)
	}
	return sf
}

func fixtureTensor(t *testing.T, fx *model.SafetensorsFile, key string) *g.Tensor {
	t.Helper()
	ten, ok := fx.Tensors[key]
	if !ok {
		t.Fatalf("fixture tensor %q missing", key)
	}
	return ten
}

// TestReadWAVFormats decodes every generated WAV variant and compares against
// the float32 ground truth python-soundfile produced for the same file.
func TestReadWAVFormats(t *testing.T) {
	fx := loadFixtures(t)
	cases := []struct {
		file     string
		key      string
		channels int
	}{
		{"pcm16_mono.wav", "wav_pcm16_mono", 1},
		{"pcm16_stereo.wav", "wav_pcm16_stereo", 2},
		{"pcm24_mono.wav", "wav_pcm24_mono", 1},
		{"pcm32_mono.wav", "wav_pcm32_mono", 1},
		{"float32_mono.wav", "wav_float32_mono", 1},
		{"float64_mono.wav", "wav_float64_mono", 1},
		{"wavex_pcm16_mono.wav", "wav_wavex_pcm16_mono", 1},
		{"wavex_float32_mono.wav", "wav_wavex_float32_mono", 1},
		{"pcm16_mono_extra_chunks.wav", "wav_pcm16_mono_extra_chunks", 1},
	}
	for _, c := range cases {
		t.Run(c.file, func(t *testing.T) {
			w, err := ReadWAV("testdata/" + c.file)
			if err != nil {
				t.Fatalf("ReadWAV: %v", err)
			}
			if w.SampleRate != 8000 {
				t.Errorf("SampleRate = %d, want 8000", w.SampleRate)
			}
			if w.Channels != c.channels {
				t.Errorf("Channels = %d, want %d", w.Channels, c.channels)
			}
			want := fixtureTensor(t, fx, c.key).Data()
			if len(w.Samples) != len(want) {
				t.Fatalf("len(Samples) = %d, want %d", len(w.Samples), len(want))
			}
			var maxAbs float64
			for i := range want {
				d := math.Abs(float64(w.Samples[i]) - float64(want[i]))
				if d > maxAbs {
					maxAbs = d
				}
			}
			if maxAbs > 1e-6 {
				t.Errorf("max abs diff vs soundfile ground truth = %g, want <= 1e-6", maxAbs)
			}
		})
	}
}

// TestReadWAVReader checks the io.ReadSeeker entry point directly.
func TestReadWAVReader(t *testing.T) {
	f, err := os.Open("testdata/pcm16_mono.wav")
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	w, err := ReadWAVReader(f)
	if err != nil {
		t.Fatalf("ReadWAVReader: %v", err)
	}
	if w.SampleRate != 8000 || w.Channels != 1 || len(w.Samples) != 256 {
		t.Errorf("got sr=%d ch=%d n=%d, want sr=8000 ch=1 n=256",
			w.SampleRate, w.Channels, len(w.Samples))
	}
}

func TestMono(t *testing.T) {
	st, err := ReadWAV("testdata/pcm16_stereo.wav")
	if err != nil {
		t.Fatalf("ReadWAV stereo: %v", err)
	}
	m := st.Mono()
	if len(m) != len(st.Samples)/2 {
		t.Fatalf("Mono length = %d, want %d", len(m), len(st.Samples)/2)
	}
	for i := range m {
		want := (st.Samples[2*i] + st.Samples[2*i+1]) / 2
		if m[i] != want {
			t.Fatalf("Mono[%d] = %g, want %g", i, m[i], want)
		}
	}

	mono, err := ReadWAV("testdata/pcm16_mono.wav")
	if err != nil {
		t.Fatalf("ReadWAV mono: %v", err)
	}
	mm := mono.Mono()
	if len(mm) != len(mono.Samples) {
		t.Fatalf("Mono passthrough length = %d, want %d", len(mm), len(mono.Samples))
	}
	for i := range mm {
		if mm[i] != mono.Samples[i] {
			t.Fatalf("Mono passthrough[%d] = %g, want %g", i, mm[i], mono.Samples[i])
		}
	}
	// Mono must return a copy, not alias the interleaved buffer.
	mm[0] += 1
	if mm[0] == mono.Samples[0] {
		t.Error("Mono aliases the Samples buffer; want a copy")
	}
}
