//go:build darwin

package audio

import (
	"math"
	"os"
	"testing"

	g "github.com/vinq1911/gorch"
	"github.com/vinq1911/gorch/model"
)

// loadFixtures loads the golden fixtures generated by make_resample_fixtures.py.
// Shared by wav_test.go and resample_test.go.
func loadFixtures(t *testing.T) *model.SafetensorsFile {
	t.Helper()
	sf, err := model.LoadSafetensors("testdata/resample_fixtures.safetensors")
	if err != nil {
		t.Fatalf("load fixtures (regenerate with audio/make_resample_fixtures.py): %v", err)
	}
	return sf
}

func fixtureTensor(t *testing.T, fx *model.SafetensorsFile, key string) *g.Tensor {
	t.Helper()
	ten, ok := fx.Tensors[key]
	if !ok {
		t.Fatalf("fixture tensor %q missing", key)
	}
	return ten
}

// TestReadWAVFormats decodes every generated WAV variant and compares against
// the float32 ground truth python-soundfile produced for the same file.
func TestReadWAVFormats(t *testing.T) {
	fx := loadFixtures(t)
	cases := []struct {
		file     string
		key      string
		channels int
	}{
		{"pcm16_mono.wav", "wav_pcm16_mono", 1},
		{"pcm16_stereo.wav", "wav_pcm16_stereo", 2},
		{"pcm24_mono.wav", "wav_pcm24_mono", 1},
		{"pcm32_mono.wav", "wav_pcm32_mono", 1},
		{"float32_mono.wav", "wav_float32_mono", 1},
		{"float64_mono.wav", "wav_float64_mono", 1},
		{"wavex_pcm16_mono.wav", "wav_wavex_pcm16_mono", 1},
		{"wavex_float32_mono.wav", "wav_wavex_float32_mono", 1},
		{"pcm16_mono_extra_chunks.wav", "wav_pcm16_mono_extra_chunks", 1},
	}
	for _, c := range cases {
		t.Run(c.file, func(t *testing.T) {
			w, err := ReadWAV("testdata/" + c.file)
			if err != nil {
				t.Fatalf("ReadWAV: %v", err)
			}
			if w.SampleRate != 8000 {
				t.Errorf("SampleRate = %d, want 8000", w.SampleRate)
			}
			if w.Channels != c.channels {
				t.Errorf("Channels = %d, want %d", w.Channels, c.channels)
			}
			want := fixtureTensor(t, fx, c.key).Data()
			if len(w.Samples) != len(want) {
				t.Fatalf("len(Samples) = %d, want %d", len(w.Samples), len(want))
			}
			var maxAbs float64
			for i := range want {
				d := math.Abs(float64(w.Samples[i]) - float64(want[i]))
				if d > maxAbs {
					maxAbs = d
				}
			}
			if maxAbs > 1e-6 {
				t.Errorf("max abs diff vs soundfile ground truth = %g, want <= 1e-6", maxAbs)
			}
		})
	}
}

// TestReadWAVReader checks the io.ReadSeeker entry point directly.
func TestReadWAVReader(t *testing.T) {
	f, err := os.Open("testdata/pcm16_mono.wav")
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	w, err := ReadWAVReader(f)
	if err != nil {
		t.Fatalf("ReadWAVReader: %v", err)
	}
	if w.SampleRate != 8000 || w.Channels != 1 || len(w.Samples) != 256 {
		t.Errorf("got sr=%d ch=%d n=%d, want sr=8000 ch=1 n=256",
			w.SampleRate, w.Channels, len(w.Samples))
	}
}

func TestMono(t *testing.T) {
	st, err := ReadWAV("testdata/pcm16_stereo.wav")
	if err != nil {
		t.Fatalf("ReadWAV stereo: %v", err)
	}
	m := st.Mono()
	if len(m) != len(st.Samples)/2 {
		t.Fatalf("Mono length = %d, want %d", len(m), len(st.Samples)/2)
	}
	for i := range m {
		want := (st.Samples[2*i] + st.Samples[2*i+1]) / 2
		if m[i] != want {
			t.Fatalf("Mono[%d] = %g, want %g", i, m[i], want)
		}
	}

	mono, err := ReadWAV("testdata/pcm16_mono.wav")
	if err != nil {
		t.Fatalf("ReadWAV mono: %v", err)
	}
	mm := mono.Mono()
	if len(mm) != len(mono.Samples) {
		t.Fatalf("Mono passthrough length = %d, want %d", len(mm), len(mono.Samples))
	}
	for i := range mm {
		if mm[i] != mono.Samples[i] {
			t.Fatalf("Mono passthrough[%d] = %g, want %g", i, mm[i], mono.Samples[i])
		}
	}
	// Mono must return a copy, not alias the interleaved buffer.
	mm[0] += 1
	if mm[0] == mono.Samples[0] {
		t.Error("Mono aliases the Samples buffer; want a copy")
	}
}

// TestWriteWAVRoundTrip: Write→Read of in-range samples must come back
// within one 16-bit quantization step (1/32768).
func TestWriteWAVRoundTrip(t *testing.T) {
	samples := make([]float32, 1000)
	for i := range samples {
		// Deterministic pseudo-signal spanning most of [-1, 1).
		samples[i] = float32(math.Sin(float64(i)*0.37)) * 0.95
	}
	samples = append(samples, 0, 0.5, -0.5, -1.0, 32767.0/32768)

	path := t.TempDir() + "/roundtrip.wav"
	if err := WriteWAV(path, 24000, samples); err != nil {
		t.Fatalf("WriteWAV: %v", err)
	}
	w, err := ReadWAV(path)
	if err != nil {
		t.Fatalf("ReadWAV: %v", err)
	}
	if w.SampleRate != 24000 {
		t.Errorf("SampleRate = %d, want 24000", w.SampleRate)
	}
	if w.Channels != 1 {
		t.Errorf("Channels = %d, want 1", w.Channels)
	}
	if len(w.Samples) != len(samples) {
		t.Fatalf("len(Samples) = %d, want %d", len(w.Samples), len(samples))
	}
	for i := range samples {
		d := math.Abs(float64(w.Samples[i]) - float64(samples[i]))
		if d >= 1.0/32768 {
			t.Errorf("sample %d: wrote %v, read %v (diff %g >= 1/32768)", i, samples[i], w.Samples[i], d)
		}
	}
}

// TestWriteWAVClipping pins the exact float→int16 conversion:
// clip(x*32768, -32768, 32767) then truncate toward zero, matching
// numpy's `np.clip(wav*32768, -32768, 32767).astype(np.int16)` in
// roundtrip_decode.py. ReadWAV divides by 32768, so each read-back
// value must equal expectedInt16/32768 exactly.
func TestWriteWAVClipping(t *testing.T) {
	cases := []struct {
		in   float32
		want int16
	}{
		{1.5, 32767},   // clipped high
		{-2.0, -32768}, // clipped low
		{1.0, 32767},   // 32768 clips to 32767
		{-1.0, -32768},
		{0.5, 16384},
		{100.7 / 32768, 100},   // truncates toward zero, not round
		{-100.7 / 32768, -100}, // toward zero for negatives too (astype semantics)
		{0, 0},
	}
	samples := make([]float32, len(cases))
	for i, c := range cases {
		samples[i] = c.in
	}
	path := t.TempDir() + "/clip.wav"
	if err := WriteWAV(path, 8000, samples); err != nil {
		t.Fatalf("WriteWAV: %v", err)
	}
	w, err := ReadWAV(path)
	if err != nil {
		t.Fatalf("ReadWAV: %v", err)
	}
	if len(w.Samples) != len(cases) {
		t.Fatalf("len(Samples) = %d, want %d", len(w.Samples), len(cases))
	}
	for i, c := range cases {
		want := float32(c.want) / 32768
		if w.Samples[i] != want {
			t.Errorf("sample %d (in=%v): read %v, want %v (int16 %d)", i, c.in, w.Samples[i], want, c.want)
		}
	}
}

// TestWriteWAVErrors: invalid sample rates must be rejected.
func TestWriteWAVErrors(t *testing.T) {
	path := t.TempDir() + "/bad.wav"
	if err := WriteWAV(path, 0, []float32{0}); err == nil {
		t.Error("WriteWAV with sampleRate 0 should fail")
	}
	if err := WriteWAV(path, -1, []float32{0}); err == nil {
		t.Error("WriteWAV with negative sampleRate should fail")
	}
}
